apiVersion: v1
kind: Service
metadata:
  labels:
    name: inventory-service
  name: inventory-service
  namespace: microservice
spec:
  # map a Service to a DNS name
  type: ExternalName
  externalName: inventoryservice.com
  imagePullSecrets:
    - name: regcred