server:
  port: 6500 # will start this service in this port

spring:
  application:
    # will register to consul using the following name
    # other services will lookup this service with this name
    name: inventory-service